/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregister;
import userdashboard.*;
import java.sql.*;
/**
 *
 * @author Noli
 */
public class LoginRegister extends javax.swing.JFrame {
    private Connection conn = null;
    /**
     * Creates new form LoginRegister
     */
    public LoginRegister(){
        try{
            String sql = "jdbc:mysql://localhost/apartment_db";
            conn = DriverManager.getConnection(sql, "root", "");
        }
        catch(SQLException ev)
        {
            System.err.println("Got an exception! ");
            System.err.println(ev.getMessage());
        }
        initComponents();
        setLocationRelativeTo(null);
        jPanel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        error_message = new javax.swing.JLabel();
        jPasswordField_Password1 = new javax.swing.JPasswordField();
        jTextField_Email1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField_confirmPassword = new javax.swing.JPasswordField();
        jTextField_lname = new javax.swing.JTextField();
        jTextField_fname = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jPasswordField_Password2 = new javax.swing.JPasswordField();
        registerB = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        error1 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png")).getImage()
        );
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(19, 34, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-35.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8w-close-window-35.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-minimize-window-35.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8ww-minimize-window-35.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 60, 60));

        jPanel2.setBackground(new java.awt.Color(92, 225, 230));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        error_message.setForeground(new java.awt.Color(255, 0, 0));
        error_message.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(error_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 200, 20));

        jPasswordField_Password1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jPasswordField_Password1.setForeground(new java.awt.Color(19, 34, 53));
        jPasswordField_Password1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 34, 53), 2, true));
        jPanel2.add(jPasswordField_Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 240, -1));

        jTextField_Email1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jTextField_Email1.setForeground(new java.awt.Color(19, 34, 53));
        jTextField_Email1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 34, 53), 2, true));
        jTextField_Email1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextField_Email1MouseMoved(evt);
            }
        });
        jTextField_Email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Email1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_Email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 240, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(19, 34, 53));
        jButton5.setText("Register");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusable(false);
        jButton5.setRequestFocusEnabled(false);
        jButton5.setRolloverEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 90, 20));

        jLabel6.setText("No account yet? ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-male-user-55.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 70, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(19, 34, 53));
        jLabel2.setText("Log In");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 110, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Username");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        Login.setBackground(new java.awt.Color(19, 34, 53));
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Log In");
        Login.setFocusable(false);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel2.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 100, 30));

        jButton4.setText("Forgot Password");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 510));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-registration-55.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel8.setText("Registration");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jPasswordField_confirmPassword.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jPasswordField_confirmPassword.setForeground(new java.awt.Color(19, 34, 53));
        jPasswordField_confirmPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 34, 53), 2, true));
        jPasswordField_confirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_confirmPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(jPasswordField_confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 340, 30));

        jTextField_lname.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jTextField_lname.setForeground(new java.awt.Color(19, 34, 53));
        jTextField_lname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 34, 53), 2, true));
        jTextField_lname.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextField_lnameMouseMoved(evt);
            }
        });
        jTextField_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lnameActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 160, 30));

        jTextField_fname.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jTextField_fname.setForeground(new java.awt.Color(19, 34, 53));
        jTextField_fname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 34, 53), 2, true));
        jTextField_fname.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextField_fnameMouseMoved(evt);
            }
        });
        jTextField_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fnameActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, 30));

        jTextField_Email.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jTextField_Email.setForeground(new java.awt.Color(19, 34, 53));
        jTextField_Email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 34, 53), 2, true));
        jTextField_Email.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextField_EmailMouseMoved(evt);
            }
        });
        jTextField_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EmailActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 340, 30));

        jPasswordField_Password2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jPasswordField_Password2.setForeground(new java.awt.Color(19, 34, 53));
        jPasswordField_Password2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 34, 53), 2, true));
        jPanel3.add(jPasswordField_Password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 340, 30));

        registerB.setBackground(new java.awt.Color(19, 225, 230));
        registerB.setForeground(new java.awt.Color(255, 255, 255));
        registerB.setText("Register");
        registerB.setFocusable(false);
        registerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBActionPerformed(evt);
            }
        });
        jPanel3.add(registerB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 100, 30));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("First Name");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel10.setText("Confirm Password");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 20));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel11.setText("Last Name");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, 20));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel12.setText("Email Address");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel13.setText("Password");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 20));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel14.setText("Username");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jTextField_username.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(19, 34, 53));
        jTextField_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 34, 53), 2, true));
        jTextField_username.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextField_usernameMouseMoved(evt);
            }
        });
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 340, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(19, 34, 53));
        jButton7.setText("Log In");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusable(false);
        jButton7.setRequestFocusEnabled(false);
        jButton7.setRolloverEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 40, 20));

        jLabel15.setText("Already registered?");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 130, 20));

        error1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 150, 20));

        error2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 140, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Blue Icon Construction Logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 350, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_lnameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_lnameMouseMoved

    }//GEN-LAST:event_jTextField_lnameMouseMoved

    private void jTextField_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lnameActionPerformed

    private void registerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBActionPerformed
        String query = " insert into users(last_name,first_name,username,email,password)" 
	      + " values (?,?,?,?,?)";
        String lastName, firstName,username,email,pass, pass2;
        char[] p, p2;
        lastName = jTextField_lname.getText(); 
        firstName = jTextField_fname.getText(); 
        username = jTextField_username.getText(); 
        email = jTextField_Email.getText(); 
        p = jPasswordField_Password2.getPassword();
        p2 = jPasswordField_confirmPassword.getPassword();
        pass = new String(p);
        pass2 = new String(p2);
        if(lastName.trim().isEmpty() || firstName.trim().isEmpty() || username.trim().isEmpty() || email.trim().isEmpty() || pass.trim().isEmpty() || pass2.trim().isEmpty())
        {
            error2.setText("All fields are required");
        }
        else
        {
            if(pass.equals(pass2)==true)
            {
                try
                {
                    PreparedStatement preparedStmt = conn.prepareStatement(query);
                    preparedStmt.setString (1, lastName);
                    preparedStmt.setString (2, firstName);
                    preparedStmt.setString (3, username);
                    preparedStmt.setString (4, email);
                    preparedStmt.setString (5, pass);

                    preparedStmt.execute();
                    
                    query = "Select * from users where last_name = ?";
                    preparedStmt = conn.prepareStatement(query);
                    preparedStmt.setString(1,lastName);
                    
                    int ID = 0;
                    ResultSet rs = preparedStmt.executeQuery();
                    while(rs.next())
                    {
                        ID = rs.getInt("id");
                    }
                    
                    query = "INSERT INTO apartment(user_id,name,address,no_of_units) VALUES(?,'','',0)";
                    preparedStmt = conn.prepareStatement(query);
                    preparedStmt.setInt(1,ID);
                    preparedStmt.execute();
                }
                catch(SQLException e)
                {
                    System.err.println(e);
                }
                
                jPanel3.setVisible(false);
                jPanel2.setVisible(true);
            }
            else
            {
                error1.setText("Password doesn't match");
            }
        }
        
    }//GEN-LAST:event_registerBActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField_Email1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_Email1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Email1MouseMoved

    private void jTextField_Email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Email1ActionPerformed

    private void jTextField_EmailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_EmailMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmailMouseMoved

    private void jTextField_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EmailActionPerformed

    private void jTextField_fnameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_fnameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fnameMouseMoved

    private void jTextField_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fnameActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fnameActionPerformed

    private void jPasswordField_confirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_confirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_confirmPasswordActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String query = " SELECT * FROM users WHERE username = ?" ;
        
        String username,pass;
        char[] p;
        username = jTextField_Email1.getText();
        p = jPasswordField_Password1.getPassword();
        pass = new String(p);
        try
        {
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString (1, username);

            ResultSet rs = preparedStmt.executeQuery();
            int ctr = 0;
            while(rs.next())
            {
                String password = rs.getString("password");
                if(password.equals(pass)==true)
                {
                    ctr++;
                    int id = rs.getInt("id");
                    UserDashboard UD = new UserDashboard(id);
                    UD.setVisible(true);
                    this.dispose();
                }
                      
            
            }
            if(ctr==0)
            {
                error_message.setText("Incorrect Username or Password");
                
            }
            
         
        }
        catch(SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void jTextField_usernameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usernameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameMouseMoved

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error_message;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField_Password1;
    private javax.swing.JPasswordField jPasswordField_Password2;
    private javax.swing.JPasswordField jPasswordField_confirmPassword;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Email1;
    private javax.swing.JTextField jTextField_fname;
    private javax.swing.JTextField jTextField_lname;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JButton registerB;
    // End of variables declaration//GEN-END:variables
}
